export const INITIAL_WAVE_INTERVAL = 20000; // 20 seconds between waves initially
export const MAX_MATH_BLOCKS = 3; // Maximum number of math blocks on screen at once
export const PADDING = 0.05; // 5% padding on each side
export const SHOOT_COOLDOWN = 700; // Increase cooldown to 700ms for even less frequent shooting
export const INITIAL_ZOMBIES_PER_WAVE = 20; // Reduced from 3
export const ZOMBIES_PER_WAVE_INCREMENT = 1.5; // Reduced from 1
export const PLAYER_GAP = 3; // Increased from 2 to create a small visible gap
export const PLAYER_WIDTH = 15;
export const PLAYER_HEIGHT = 15;
export const FORMATION_ROWS = 3;
export const MAX_FORMATION_WIDTH = 10;
export const TOTAL_ZOMBIE_FRAMES = 8; // Adjust this based on the actual number of zombie frames
export const ZOMBIE_ANIMATION_FRAME_DURATION = 50; // milliseconds per frame (adjust for desired speed)
export const ZOMBIE_RADIUS = 7.5; // Half of the zombie width/height
export const ZOMBIE_REPULSION_FORCE = 0.2; // Adjust this value to control how strongly zombies repel each other
export const PLAYER_SPEED = 5; // Reduced from 10 to slow down left/right movement
export const BULLET_SPEED = 18; // Increased from 15 to 18
export const CLICK_TIMEOUT = 1000; // Reduced from 5000 to 1000 milliseconds (1 second)
export const ZOMBIE_MIN_SCALE = 1;
export const ZOMBIE_MAX_SCALE = 3; // Changed from 1.5 to 3
export const BASE_ZOMBIE_SPEED = 0.8; // Adjust this value as needed
export const SPEED_INCREMENT_PER_WAVE = 0.03; // Adjust this value as needed
export const ANIMATION_FRAME_DURATION = 100; // milliseconds per frame
export const TOTAL_FRAMES = 15; // Assuming 15 frames for player animation
export const SHOOT_CHANCE_PER_PLAYER = 0.03; // Decrease chance to shoot to 3% per frame
export const INITIAL_BOSS_HEALTH = 15;
export const BOSS_HEALTH_INCREMENT = 3;
export const INITIAL_BOSS_SCALE = 2;
export const BOSS_SCALE_INCREMENT = 0.2;
export const BOSS_HEALTH_MULTIPLIER = 10; // Increase from 5 to 7 for more strength
export const BOSS_DAMAGE_MULTIPLIER = 6; // Increase from 5 to 6
export const ZOMBIE_ATTACK_COOLDOWN = 1000; // 1 second cooldown for regular zombies
export const BOSS_ATTACK_COOLDOWN = 1000; // 1 second cooldown for boss zombies
export const BOSS_PLAYERS_ELIMINATED_PER_ATTACK = 12; // Increase from 10 to 12
export const BOSS_SPAWN_INTERVAL = 20000; // 45 seconds between boss spawns (adjusted from 60000)
export const BOSS_SPEED = 0.8; // Slower speed for the boss
export const BOSS_WAVE_FREQUENCY = 2; // Boss appears every 2nd wave
export const FIRST_BOSS_WAVE = 2; // First boss appears after the 2nd wave
export const WAVE_DURATION = 10000; // 10 seconds per wave
export const INITIAL_MATH_BLOCK_VALUE_MIN = -5;
export const INITIAL_MATH_BLOCK_VALUE_MAX = -3;
export const MATH_BLOCK_VALUE_WAVE_MULTIPLIER = 1.3; // This will be used to scale the values for subsequent waves
export const MATH_BLOCK_SPEED = 1.2; // Base speed
export const MATH_BLOCK_SPEED_INCREMENT = 0.01; // 1% increase per wave
export const MAX_SINGLE_SOUND_PLAYERS = 6;
export const LASER_SINGLE_SOUND = "/audio/laser_single.mp3";
export const LASER_MULTIPLE_SOUND = "/audio/laser_multiple.mp3";
export const MAX_ZOMBIES_PER_WAVE = 300; // Maximum number of zombies per wave
export const PADDING_TOP = 40;
export const BOTTOM_PADDING = 40; // Add this export constant if not already present
export const MATH_BLOCK_HIT_COOLDOWN_NEGATIVE = 30; // ms for negative values
export const MATH_BLOCK_VALUES = {
	health: 80, // Decreased from 100
	damage: 15, // Decreased from 20
	points: 40, // Decreased from 50
};
export const MAX_NEGATIVE_VALUE = -100;
export const MAX_NEGATIVE_RANGE_START = -150;
export const MAX_NEGATIVE_RANGE_END = -100;
export const BASE_MATH_BLOCK_HIT_COOLDOWN_POSITIVE = 300; // Base cooldown for positive blocks in milliseconds
export const MATH_BLOCK_COOLDOWN_INCREMENT = 0.01; // 1% increase per wave
export const BULLET_TRAIL_LENGTH = 5; // Number of positions to keep in the trail
export const MATH_BLOCK_SPAWN_INTERVAL = 5000; // 5 seconds between spawn attempts
export const MATH_BLOCK_SPAWN_CHANCE = 0.5; // 50% chance to spawn when the interval is reached
export const TOTAL_PLAYER_FRAMES = 15;
export const COOLDOWN_RADIUS = 20; // Increased from 15 to 20
export const COOLDOWN_STROKE_WIDTH = 3;
export const LOCKER_SIZE = 24; // Slightly increased from 20 to 24 for better visibility
